version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  generating-config:
    jobs:
      - path-filtering/filter:
            base-revision: main
            config-path: .circle/build-code-config.yml
            mapping: |
              env/dev/* build-dev-env true
              env/stg/* build-stg-env true
#      - deploy-batch:
#          name: dev-duffy-batch-commission
#          env: dev
#          filters:
#            tags:
#              only: /^v.*_commission-register.*/
#            branches:
#              ignore: /.*/
#      - deploy-batch-end-notify:
#          requires:
#            - dev-duffy-batch-commission
#          name: dev-duffy-batch-commission-end-notify
#          env: dev
#          filters:
#            tags:
#              only: /^v.*_commission-register.*/
#            branches:
#              ignore: /.*/