
version: 2.1

parameters:
  build-dev-env:
    type: boolean
    default: false
  build-stg-env:
    type: boolean
    default: false


jobs:
  deploy-batch:
    docker:
      - image: cimg/python:3.9
    parallelism: 15
    parameters:
      app:
        type: string
      env:
        type: string
    environment:
      AWS_RETRY_MODE: standard
      AWS_MAX_ATTEMPTS: 17
    steps:
      - checkout
      - run:
          name: Deploy duffy-batch-commission
          command: echo "deploy batch" << parameters.env >>  << parameters.app >>

  deploy-batch-end-notify:
    docker:
      - image: cimg/python:3.9
    parameters:
      app:
        type: string
      env:
        type: string
    steps:
      - checkout
      - run:
          name: deploy-batch-end-notify
          command: echo "notify" << parameters.env >>  << parameters.app >>


workflows:
  version: 2
  deploy-always:
    jobs:
      - deploy-batch:
          name: dev-duffy-batch-commission
          env: always
          app: commission-register
      - deploy-batch-end-notify:
          requires:
            - dev-duffy-batch-commission
          name: dev-duffy-batch-commission-end-notify
          env: always
  deploy-dev:
    when: << pipeline.parameters.build-dev-env >>
    jobs:
      - deploy-batch:
          name: dev-duffy-batch-commission
          env: dev
          app: commission-register
      - deploy-batch-end-notify:
          requires:
            - dev-duffy-batch-commission
          name: dev-duffy-batch-commission-end-notify
          env: dev
          app: commission-register
  deploy-stg:
    when: << pipeline.parameters.build-stg-env >>
    jobs:
      - deploy-batch:
          name: dev-duffy-batch-commission
          env: stg
          app: commission-register
      - deploy-batch-end-notify:
          requires:
            - dev-duffy-batch-commission
          name: dev-duffy-batch-commission-end-notify
          env: stg
          app: commission-register
