version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  generating-config:
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/config-build.yml
          mapping: |
            env/dev/* build-dev-env true
            env/stg/* build-stg-env true
          filters:
            tags:
              ignore: /.*/
            branches:
              only: main