version: 2.1

orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  version: 2
  generating-config:
    jobs:
      - path-filtering/filter:
            base-revision: main
            mapping: |
              env/dev/* deploy-dev true .circleci/build-code-config.yml
              env/stg/* deploy-stg true .circleci/build-docs-config.yml
      - deploy-batch:
          name: dev-duffy-batch-commission
          env: dev
          filters:
            tags:
              only: /^v.*_commission-register.*/
            branches:
              ignore: /.*/
      - deploy-batch-end-notify:
          requires:
            - dev-duffy-batch-commission
          name: dev-duffy-batch-commission-end-notify
          env: dev
          filters:
            tags:
              only: /^v.*_commission-register.*/
            branches:
              ignore: /.*/