
version: 2.1

parameters:
  build-dev-env:
    type: boolean
    default: false
  build-stg-env:
    type: boolean
    default: false


jobs:
  deploy-batch:
    docker:
      - image: cimg/python:3.9
    parallelism: 15
    parameters:
      env:
        type: string
    environment:
      AWS_RETRY_MODE: standard
      AWS_MAX_ATTEMPTS: 17
    steps:
      - checkout
      - run:
          name: Deploy duffy-batch-commission
#          working_directory: aws/shell
          command: echo "deploy batch"

  deploy-batch-end-notify:
    docker:
      - image: cimg/python:3.9
    parameters:
      env:
        type: string
    steps:
      - checkout
      - run:
          name: deploy-batch-end-notify
          command: echo "notify"


workflows:
  version: 2
  # deploy dev
  deploy-dev:
    when: << pipeline.parameters.build-dev-env >>
    jobs:
      - deploy-batch:
          name: dev-duffy-batch-commission
          env: dev
#          filters:
#            tags:
#              only: /^v.*_commission-register.*/
#            branches:
#              ignore: /.*/
      - deploy-batch-end-notify:
          requires:
            - dev-duffy-batch-commission
          name: dev-duffy-batch-commission-end-notify
          env: dev
#          filters:
#            tags:
#              only: /^v.*_commission-register.*/
#            branches:
#              ignore: /.*/
  deploy-stg:
    when: << pipeline.parameters.build-stg-env >>
    jobs:
      - deploy-batch:
          name: dev-duffy-batch-commission
          env: stg
      - deploy-batch-end-notify:
          requires:
            - dev-duffy-batch-commission
          name: dev-duffy-batch-commission-end-notify
          env: stg